apiVersion: v1
kind: Secret
metadata:
  name: paycash-secrets
  namespace: paycash
  labels:
    app.kubernetes.io/part-of: paycash-platform
type: Opaque
stringData:
  # TODO: replace with a real secret (kubectl create secret / SOPS / sealed-secrets)
  JWT_SECRET: "paycash-jwt-secret-key-2024"
  HMAC_SECRET: "paycash-default-secret-2024"
  SMTP_USER: "notifications@paycash.cm"
